plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':service-incident')
    implementation project(':service-problem')
    implementation project(':service-user')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    runtimeOnly 'com.oracle.database.jdbc:ojdbc11:23.3.0.23.09'
}

springBoot {
    mainClass = 'com.openitsm.application.Application'
}