spring:
  datasource:
    url: jdbc:oracle:thin:@//***.***.*.***:****/ORCLPDB
    username: vnrvjiet
    password: vnr
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
